title: Searching for mechanistic understanding of nature
description: A collection of my projects and tools.
url: "http://nvladimus.github.io"
markdown: kramdown
highlighter: rouge
permalink: /blog/:year/:month/:day/:title

theme: jekyll-theme-minimal
