title: Tools and ideas
description: A collection of scientific topics which I find particularly exciting.
url: "http://nvladimus.github.io"
markdown: kramdown
highlighter: rouge
permalink: /blog/:year/:month/:day/:title

theme: jekyll-theme-minimal
