title: Tools and ideas
description: A collection of my projects and tools for some mechanical understanding of nature.
url: "http://nvladimus.github.io"
markdown: kramdown
highlighter: rouge
permalink: /blog/:year/:month/:day/:title

theme: jekyll-theme-minimal
